lib/farm_web/router.ex
defmodule FarmWeb.Router do
  use FarmWeb, :router

  import FarmWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FarmWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FarmWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", FarmWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    resources "/cows", CowController
  end

  scope "/", FarmWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  scope "/", FarmWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/", PageController, :index

    # Animals

    resources "/donkeys", DonkeyController
    resources "/cows", CowController
    resources "/calfs", CalfController
    resources "/sheep", SheepController

    # HR
    resources "/workers", WorkerController
    resources "/patrons", PatronController
    resources "/roles", RoleController
    resources "/duties", DutyController


    # LAND
    resources "/arable", ArableController
    resources "/paddocks", PaddockController


    # PRODUCTION
    resources "/products", ProductController
    resources "/crops", CropController
    resources "/milks", MilkController
    resources "/feeds", FeedsController
    resources "/feedings", FeedingController

    # OTHERS
    resources "/machinerys", MachineryController
    resources "/medications", MedicationController
    resources "/photos", PhotoController
    resources "/events", EventController

    # Finance
    resources "/sales", SalesController
    resources "/purchases", PurchasesController
    resources "/salarys", SalaryController
    resources "/customers", CustomerController


  end

  pipeline :api_authenticated do
    plug FarmWeb.AuthAccessPipeline
  end

  # Other scopes may use custom stacks.
  scope "/api", FarmWeb.Api, as: :api do
    pipe_through :api

    #Products
    resources "/calfs", CalfController
    resources "/milks", MilkController
    # resources "/cows", CowController
    get "/cows/total", CowController, :total_number
    resources "/donkeys", DonkeyController
    resources "/events", EventController

    #Inventory
    resources "/machinerys", MachineryController
    resources "/medications", MedicationController

    # HR
    resources "/workers", WorkerController
    resources "/duties", DutyController
    resources "/roles", RoleController
    resources "/patrons", PatronController

    # Land
    resources "/arable", ArableController
    resources "/paddocks", PaddockController

    # Products
    resources "/products", ProductController

    # Finance
    resources "/sales", SalesController
    resources "/procurements", ProcurementsController
    resources "/salarys", SalaryController

    # Accounts
    post "/register", UserRegistrationController, :register
    post "/sign_in", SessionController, :create
    post "/sign_out", SessionController, :delete
  end

  ## AUthenticated api routes

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: FarmWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes


end

lib/farm/hr/patron.ex
defmodule Farm.HR.Patron do
  use Ecto.Schema
  import Ecto.Changeset
  alias Farm.HR.Role

  schema "patrons" do
    field :address, :string
    field :name, :string
    field :phone_number, :integer
    belongs_to :role, Role
    has_many(:cows, Farm.Animals.Cow)

    timestamps()
  end

  @doc false
  def changeset(patron, attrs) do
    patron
    |> cast(attrs, [:name, :phone_number, :address, :role_id])
    |> validate_required([:name, :phone_number, :address, :role_id])
  end
end

lib/farm_web/controllers/api/patron_controller.ex
defmodule FarmWeb.Api.PatronController do
  use FarmWeb, :controller

  alias Farm.HR
  alias Farm.HR.Patron

  action_fallback FarmWeb.FallbackController

  def index(conn, role) do
    patrons = HR.list_patrons(role)
    render(conn, "index.json", patrons: patrons, role: role)
  end

  def create(conn, %{"patron" => patron_params}) do
    with {:ok, %Patron{} = patron} <- HR.create_patron(patron_params) do
      conn
      |> put_status(:created)
      |> put_resp_header("location", Routes.api_patron_path(conn, :show, patron))
      |> render("show.json", patron: patron)
    end
  end

  def show(conn, %{"id" => id}) do
    patron = HR.get_patron!(id)
    render(conn, "show.json", patron: patron)
  end

  def update(conn, %{"id" => id, "patron" => patron_params}) do
    patron = HR.get_patron!(id)

    with {:ok, %Patron{} = patron} <- HR.update_patron(patron, patron_params) do
      render(conn, "show.json", patron: patron)
    end
  end

  def delete(conn, %{"id" => id}) do
    patron = HR.get_patron!(id)

    with {:ok, %Patron{}} <- HR.delete_patron(patron) do
      send_resp(conn, :no_content, "")
    end
  end
end

lib/farm_web/controllers/patron_controller.ex
defmodule FarmWeb.PatronController do
  use FarmWeb, :controller

  alias Farm.HR
  alias Farm.HR.Patron
  alias Farm.HR.Role
  import Ecto.Query

  def index(conn, _params) do

    preloads = [:role, :cows]
    patrons = HR.list_patrons(preloads: preloads)
    render(conn, "index.html", patrons: patrons)

  end

  def new(conn, _params) do
    changeset = HR.change_patron(%Patron{})
    role_query = from(r in Role, select: {r.name, r.id})
    all_roles = Farm.Repo.all(role_query)
    render(conn, "new.html", changeset: changeset, all_roles: all_roles)
  end

  def create(conn, %{"patron" => patron_params}) do
    case HR.create_patron(patron_params) do
      {:ok, patron} ->
        conn
        |> put_flash(:info, "Patron created successfully.")
        |> redirect(to: Routes.patron_path(conn, :show, patron))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    patron = HR.get_patron!(id)
    render(conn, "show.html", patron: patron)
  end
  # def show(conn, %{"id" => id}) do
  #   patron = HR.get_patron!(id)
  #   role_query = from(r in Role, select: {r.name, r.id})
  #   all_roles = Farm.Repo.all(role_query)
  #   render(conn, "show.html", patron: patron, all_roles: all_roles)
  # end

  # def show_patrons_details(opts \\ []) do
  #   roles =

  #     Patron
  #     |> Repo.all(Patron)
  #     |> Repo.preload(roles)
  #   end

  def edit(conn, %{"id" => id}) do
    patron = HR.get_patron!(id)
    changeset = HR.change_patron(patron)
    render(conn, "edit.html", patron: patron, changeset: changeset)
  end

  def update(conn, %{"id" => id, "patron" => patron_params}) do
    patron = HR.get_patron!(id)

    case HR.update_patron(patron, patron_params) do
      {:ok, patron} ->
        conn
        |> put_flash(:info, "Patron updated successfully.")
        |> redirect(to: Routes.patron_path(conn, :show, patron))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", patron: patron, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    patron = HR.get_patron!(id)
    {:ok, _patron} = HR.delete_patron(patron)

    conn
    |> put_flash(:info, "Patron deleted successfully.")
    |> redirect(to: Routes.patron_path(conn, :index))
  end
end

lib/farm_web/views/patron_view.ex
defmodule FarmWeb.PatronView do
  use FarmWeb, :view
end

lib/farm_web/templates/patron/edit.html.heex
<h1>Edit Patron</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.patron_path(@conn, :update, @patron)) %>

<span><%= link "Back", to: Routes.patron_path(@conn, :index) %></span>

lib/farm_web/templates/patron/form.html.heex
<.form let={f} for={@changeset} action={@action}>
    <%= if @changeset.action do %>
        <div class="alert alert-danger">
            <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
        <% end %>

            <div class="mb-3">
                <%= label f, :name, class: "form-label" %>
                    <%= text_input f, :name, class: "form-control" %>
                        <%= error_tag f, :name %>
            </div>

            <div class="mb-3">
                <%= label f, :phone_number %>
                    <%= number_input f, :phone_number %>
                        <%= error_tag f, :phone_number %>
            </div>
            <div class="mb-3">
                <%= label f, :address %>
                    <%= text_input f, :address %>
                        <%= error_tag f, :address %>
            </div>
            <div class="mb-3">
                <%= label f, :role %>
                    <%= select(f, :role_id, @all_roles) %>
                        <%= error_tag f, :role_id %>
            </div>

            <div class="mb-3">
                <%= submit "Save", phx_disable_with: "Saving...", class: "btn btn-primary" %>
            </div>
</.form>

lib/farm_web/templates/patron/index.html.heex
<table class="table table-hover table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Adress</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <%= for patron <- @patrons do %>
            <tr>
                <th scope="row">
                    <%= patron.id %>
                </th>
                <td>
                    <%= patron.name %>
                </td>
                <td>
                    <%= patron.address %>
                </td>
                <td>
                    <%= patron.phone_number %>
                </td>
                <td>

                    <%= patron.role.name %>
                </td>
                <td>
                    <span><%= link "S", class: "i bx-message-square-detail ", to: Routes.patron_path(@conn, :show, patron) %></span>
                    <span><%= link "E", class: "bx:bxs-edit-alt ", to: Routes.patron_path(@conn, :edit, patron) %></span>
                    <span><%= link "D", class: "bx:trash", to: Routes.patron_path(@conn, :delete, patron), method: :delete, data: [confirm: "Are you sure?"] %></span>
                </td>
            </tr>

            <% end %>
    </tbody>
</table>

<span><%= link "Add patron", to: Routes.patron_path(@conn, :new) %></span>

lib/farm_web/templates/patron/new.html.heex
<h1>New Patron</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.patron_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.patron_path(@conn, :index) %></span>

lib/farm_web/templates/patron/show.html.heex
<h1>Show Patron</h1>

<ul>

    <li>
        <strong>Name:</strong>
        <%= @patron.name %>
    </li>

    <li>
        <strong>Phone number:</strong>
        <%= @patron.phone_number %>
    </li>

    <li>
        <strong>Address:</strong>
        <%= @patron.address %>
    </li>

    <li>
        <strong>Role:</strong>
        <%= @patron.role.name %>
    </li>
    <li>

        <strong>Cows:</strong>
        <%= for cow <- @patron.cows do %>
            <ol>
                <span>
   
                        <%= link cow.name, to: Routes.cow_path(@conn, :show, cow) %></span> |
            </ol>
            <% end %>
    </li>

</ul>

<span><%= link "Edit", to: Routes.patron_path(@conn, :edit, @patron) %></span> |
<span><%= link "Back", to: Routes.patron_path(@conn, :index) %></span>